version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: polystrike_postgres
    restart: unless-stopped
    ports:
      - "15432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: polystrike
    volumes:
      - polystrike_pg:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: polystrike_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - polystrike_redis:/data

volumes:
  polystrike_pg:
  polystrike_redis:
